// AI API Management Types

export type AIAPICategory =
  | 'core_ai_models'
  | 'seo_content_generation'
  | 'keyword_seo_data'
  | 'scraping_lead_extraction'
  | 'email_lead_enrichment'
  | 'social_media_automation'
  | 'chat_support_ai'
  | 'voice_translation'
  | 'image_design_ai'
  | 'automation_workflow'
  | 'analytics_tracking'
  | 'bonus_high_impact';

export type AIAPICategoryId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;

export type RequestType = 'seo' | 'chat' | 'critical' | 'image' | 'voice' | 'translation' | 'automation' | 'analytics';

export interface AIAPIIntegration {
  id: string;
  name: string;
  provider: string;
  category: AIAPICategory;
  sub_category?: string;
  api_key?: string;
  api_endpoint?: string;
  priority: number; // 1 = primary, 2+ = fallback
  is_active: boolean;
  is_enabled: boolean; // Master on/off switch
  billing_enabled: boolean; // Billing control
  cost_per_1k_tokens: number;
  max_tokens_per_request: number;
  daily_budget_limit?: number;
  daily_cost_today: number;
  tokens_used_today: number;
  requests_today: number;
  last_used_at?: string;
  last_error_at?: string;
  last_error_message?: string;
  fail_count: number;
  auto_failover_enabled: boolean;
  usage_mapping: RequestType[];
  config: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface AIAPIUsageLog {
  id: string;
  api_integration_id: string;
  user_id?: string;
  request_type: RequestType;
  tokens_used: number;
  cost: number;
  response_time_ms?: number;
  status: 'success' | 'failed' | 'fallback';
  fallback_from_id?: string;
  error_message?: string;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface AIAPIProvider {
  id: string;
  provider: string;
  name: string;
  category_id: AIAPICategoryId;
  category: AIAPICategory;
  sub_category?: string;
  api_endpoint: string;
  default_cost_per_1k_tokens: number;
  default_max_tokens: number;
  supported_request_types: RequestType[];
  requires_api_key: boolean;
  documentation_url?: string;
}

export interface AIAPIRequest {
  request_type: RequestType;
  prompt: string;
  max_tokens?: number;
  temperature?: number;
  model?: string;
  metadata?: Record<string, unknown>;
}

export interface AIAPIResponse {
  success: boolean;
  data?: string;
  tokens_used: number;
  cost: number;
  response_time_ms: number;
  api_provider: string;
  fallback_used?: boolean;
  fallback_from?: string;
  error?: string;
}

export interface AIAPIUsageStats {
  total_requests: number;
  total_tokens: number;
  total_cost: number;
  avg_response_time: number;
  success_rate: number;
  by_request_type: {
    [key in RequestType]: {
      requests: number;
      tokens: number;
      cost: number;
    };
  };
  by_provider: {
    [provider: string]: {
      requests: number;
      tokens: number;
      cost: number;
      success_rate: number;
    };
  };
}

export interface AIAPIConfig {
  primary_provider: string;
  fallback_providers: string[];
  auto_failover: boolean;
  max_retries: number;
  timeout_ms: number;
  usage_mapping: {
    [key in RequestType]: {
      preferred_provider: string;
      fallback_providers: string[];
    };
  };
}

export interface CostControlConfig {
  daily_budget_limit?: number;
  monthly_budget_limit?: number;
  max_tokens_per_request: number;
  alert_threshold_percent: number;
  enable_auto_pause: boolean;
}

export interface AIAPIHealthStatus {
  provider: string;
  is_healthy: boolean;
  last_check: string;
  avg_response_time: number;
  success_rate: number;
  fail_count: number;
  is_within_budget: boolean;
  is_rate_limited: boolean;
}

// All 105 AI Providers
export const AI_PROVIDERS: AIAPIProvider[] = [
  // 1. CORE AI MODELS (PRIMARY + FALLBACK)
  {
    id: 'openai',
    provider: 'openai',
    name: 'OpenAI (GPT series)',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.openai.com/v1',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat', 'critical'],
    requires_api_key: true,
    documentation_url: 'https://platform.openai.com/docs',
  },
  {
    id: 'google-gemini',
    provider: 'google-gemini',
    name: 'Google Gemini',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://generativelanguage.googleapis.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 8192,
    supported_request_types: ['seo', 'chat', 'critical'],
    requires_api_key: true,
    documentation_url: 'https://ai.google.dev/docs',
  },
  {
    id: 'anthropic-claude',
    provider: 'anthropic-claude',
    name: 'Anthropic Claude',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.anthropic.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat', 'critical'],
    requires_api_key: true,
    documentation_url: 'https://docs.anthropic.com',
  },
  {
    id: 'mistral',
    provider: 'mistral',
    name: 'Mistral',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.mistral.ai',
    default_cost_per_1k_tokens: 0.0007,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.mistral.ai',
  },
  {
    id: 'groq',
    provider: 'groq',
    name: 'Groq (fast inference)',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.groq.com',
    default_cost_per_1k_tokens: 0.0001,
    default_max_tokens: 8192,
    supported_request_types: ['seo', 'chat', 'critical'],
    requires_api_key: true,
    documentation_url: 'https://console.groq.com/docs',
  },
  {
    id: 'together-ai',
    provider: 'together-ai',
    name: 'Together AI',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.together.xyz',
    default_cost_per_1k_tokens: 0.0006,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.together.ai',
  },
  {
    id: 'openrouter',
    provider: 'openrouter',
    name: 'OpenRouter (multi-model)',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://openrouter.ai/api',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat', 'critical'],
    requires_api_key: true,
    documentation_url: 'https://openrouter.ai/docs',
  },
  {
    id: 'deepseek',
    provider: 'deepseek',
    name: 'DeepSeek',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.deepseek.com',
    default_cost_per_1k_tokens: 0.0001,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat'],
    requires_api_key: true,
    documentation_url: 'https://platform.deepseek.com/api-docs',
  },
  {
    id: 'perplexity',
    provider: 'perplexity',
    name: 'Perplexity API',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.perplexity.ai',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.perplexity.ai',
  },
  {
    id: 'cohere',
    provider: 'cohere',
    name: 'Cohere',
    category_id: 1,
    category: 'core_ai_models',
    api_endpoint: 'https://api.cohere.ai',
    default_cost_per_1k_tokens: 0.0015,
    default_max_tokens: 4096,
    supported_request_types: ['seo', 'chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.cohere.com',
  },

  // 2. SEO CONTENT GENERATION (HIGH VALUE)
  {
    id: 'writesonic',
    provider: 'writesonic',
    name: 'Writesonic API',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.writesonic.com',
    default_cost_per_1k_tokens: 0.01,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.writesonic.com',
  },
  {
    id: 'copy-ai',
    provider: 'copy-ai',
    name: 'Copy.ai',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.copy.ai',
    default_cost_per_1k_tokens: 0.015,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.copy.ai',
  },
  {
    id: 'jasper-ai',
    provider: 'jasper-ai',
    name: 'Jasper AI',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.jasper.ai',
    default_cost_per_1k_tokens: 0.02,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.jasper.ai',
  },
  {
    id: 'rytr',
    provider: 'rytr',
    name: 'Rytr',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.rytr.me',
    default_cost_per_1k_tokens: 0.008,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.rytr.me',
  },
  {
    id: 'anyword',
    provider: 'anyword',
    name: 'Anyword',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.anyword.com',
    default_cost_per_1k_tokens: 0.012,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.anyword.com',
  },
  {
    id: 'scalenut',
    provider: 'scalenut',
    name: 'Scalenut',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.scalenut.com',
    default_cost_per_1k_tokens: 0.01,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.scalenut.com',
  },
  {
    id: 'outranking',
    provider: 'outranking',
    name: 'Outranking',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.outranking.com',
    default_cost_per_1k_tokens: 0.015,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.outranking.com',
  },
  {
    id: 'frase',
    provider: 'frase',
    name: 'Frase',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.frase.io',
    default_cost_per_1k_tokens: 0.018,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.frase.io',
  },
  {
    id: 'surferseo-ai',
    provider: 'surferseo-ai',
    name: 'SurferSEO AI',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.surferseo.com',
    default_cost_per_1k_tokens: 0.02,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.surferseo.com',
  },
  {
    id: 'neuronwriter',
    provider: 'neuronwriter',
    name: 'NeuronWriter',
    category_id: 2,
    category: 'seo_content_generation',
    api_endpoint: 'https://api.neuronwriter.com',
    default_cost_per_1k_tokens: 0.01,
    default_max_tokens: 2000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://docs.neuronwriter.com',
  },

  // 3. KEYWORD + SEO DATA
  {
    id: 'dataforseo',
    provider: 'dataforseo',
    name: 'DataForSEO',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'keyword_research',
    api_endpoint: 'https://api.dataforseo.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://docs.dataforseo.com',
  },
  {
    id: 'serpapi',
    provider: 'serpapi',
    name: 'SerpAPI',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'serp',
    api_endpoint: 'https://serpapi.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://serpapi.com/docs',
  },
  {
    id: 'zenserp',
    provider: 'zenserp',
    name: 'Zenserp',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'serp',
    api_endpoint: 'https://api.zenserp.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://docs.zenserp.com',
  },
  {
    id: 'serper-dev',
    provider: 'serper-dev',
    name: 'Serper.dev',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'serp',
    api_endpoint: 'https://serper.dev',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://serper.dev/docs',
  },
  {
    id: 'google-search-console',
    provider: 'google-search-console',
    name: 'Google Search Console API',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'analytics',
    api_endpoint: 'https://www.googleapis.com/webmasters/v3',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://developers.google.com/webmaster-tools',
  },
  {
    id: 'google-trends',
    provider: 'google-trends',
    name: 'Google Trends API',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'trends',
    api_endpoint: 'https://trends.google.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://developers.google.com/trends',
  },
  {
    id: 'ahrefs',
    provider: 'ahrefs',
    name: 'Ahrefs (limited)',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'backlinks',
    api_endpoint: 'https://apiv2.ahrefs.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://ahrefs.com/api',
  },
  {
    id: 'semrush',
    provider: 'semrush',
    name: 'SEMrush API',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'keyword_research',
    api_endpoint: 'https://api.semrush.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['seo', 'analytics'],
    requires_api_key: true,
    documentation_url: 'https://www.semrush.com/api',
  },
  {
    id: 'keywordtool',
    provider: 'keywordtool',
    name: 'KeywordTool API',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'keyword_research',
    api_endpoint: 'https://api.keywordtool.io',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 1000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://keywordtool.io/api',
  },
  {
    id: 'ubersuggest',
    provider: 'ubersuggest',
    name: 'Ubersuggest API',
    category_id: 3,
    category: 'keyword_seo_data',
    sub_category: 'keyword_research',
    api_endpoint: 'https://api.neilpatel.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 1000,
    supported_request_types: ['seo'],
    requires_api_key: true,
    documentation_url: 'https://neilpatel.com/api',
  },

  // 4. SCRAPING + LEAD EXTRACTION
  {
    id: 'apify',
    provider: 'apify',
    name: 'Apify',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.apify.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.apify.com',
  },
  {
    id: 'brightdata',
    provider: 'brightdata',
    name: 'BrightData',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.brightdata.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.brightdata.com',
  },
  {
    id: 'scraperapi',
    provider: 'scraperapi',
    name: 'ScraperAPI',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.scraperapi.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.scraperapi.com',
  },
  {
    id: 'diffbot',
    provider: 'diffbot',
    name: 'Diffbot',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.diffbot.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.diffbot.com',
  },
  {
    id: 'zyte',
    provider: 'zyte',
    name: 'Zyte (Scrapinghub)',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.zyte.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.zyte.com',
  },
  {
    id: 'phantombuster',
    provider: 'phantombuster',
    name: 'PhantomBuster',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.phantombuster.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.phantombuster.com',
  },
  {
    id: 'texau',
    provider: 'texau',
    name: 'TexAu',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.texau.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.texau.com',
  },
  {
    id: 'octoparse',
    provider: 'octoparse',
    name: 'Octoparse API',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.octoparse.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.octoparse.com',
  },
  {
    id: 'webscraper-io',
    provider: 'webscraper-io',
    name: 'WebScraper.io',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.webscraper.io',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.webscraper.io',
  },
  {
    id: 'proxycrawl',
    provider: 'proxycrawl',
    name: 'Proxycrawl',
    category_id: 4,
    category: 'scraping_lead_extraction',
    api_endpoint: 'https://api.proxycrawl.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 5000,
    supported_request_types: ['seo', 'automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.proxycrawl.com',
  },

  // 5. EMAIL + LEAD ENRICHMENT
  {
    id: 'hunter-io',
    provider: 'hunter-io',
    name: 'Hunter.io',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.hunter.io',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://hunter.io/api',
  },
  {
    id: 'snov-io',
    provider: 'snov-io',
    name: 'Snov.io',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.snov.io',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://snov.io/api',
  },
  {
    id: 'clearbit',
    provider: 'clearbit',
    name: 'Clearbit',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.clearbit.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://clearbit.com/docs',
  },
  {
    id: 'apollo',
    provider: 'apollo',
    name: 'Apollo API',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.apollo.io',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://apollo.io/docs',
  },
  {
    id: 'lusha',
    provider: 'lusha',
    name: 'Lusha API',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.lusha.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://lusha.com/api',
  },
  {
    id: 'dropcontact',
    provider: 'dropcontact',
    name: 'Dropcontact',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.dropcontact.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://dropcontact.com/api',
  },
  {
    id: 'rocketreach',
    provider: 'rocketreach',
    name: 'RocketReach',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.rocketreach.co',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://rocketreach.co/api',
  },
  {
    id: 'fullcontact',
    provider: 'fullcontact',
    name: 'FullContact',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.fullcontact.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.fullcontact.com',
  },
  {
    id: 'peopledatalabs',
    provider: 'peopledatalabs',
    name: 'PeopleDataLabs',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.peopledatalabs.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.peopledatalabs.com',
  },
  {
    id: 'leadgenius',
    provider: 'leadgenius',
    name: 'LeadGenius',
    category_id: 5,
    category: 'email_lead_enrichment',
    api_endpoint: 'https://api.leadgenius.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://leadgenius.com/api',
  },

  // 6. SOCIAL MEDIA AUTOMATION
  {
    id: 'meta-graph',
    provider: 'meta-graph',
    name: 'Meta Graph API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://graph.facebook.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developers.facebook.com/docs/graph-api',
  },
  {
    id: 'twitter-api',
    provider: 'twitter-api',
    name: 'Twitter/X API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.twitter.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developer.twitter.com/en/docs',
  },
  {
    id: 'linkedin-api',
    provider: 'linkedin-api',
    name: 'LinkedIn API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.linkedin.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://learn.microsoft.com/en-us/linkedin/shared/references/v2/overview',
  },
  {
    id: 'buffer',
    provider: 'buffer',
    name: 'Buffer API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.bufferapp.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://buffer.com/developers',
  },
  {
    id: 'hootsuite',
    provider: 'hootsuite',
    name: 'Hootsuite API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.hootsuite.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developer.hootsuite.com/docs',
  },
  {
    id: 'socialbee',
    provider: 'socialbee',
    name: 'SocialBee API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.socialbee.io',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.socialbee.io',
  },
  {
    id: 'publer',
    provider: 'publer',
    name: 'Publer API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.publer.io',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://publer.io/docs',
  },
  {
    id: 'later',
    provider: 'later',
    name: 'Later API',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.later.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developers.later.com',
  },
  {
    id: 'sprout-social',
    provider: 'sprout-social',
    name: 'Sprout Social',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.sproutsocial.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developers.sproutsocial.com',
  },
  {
    id: 'missinglettr',
    provider: 'missinglettr',
    name: 'Missinglettr',
    category_id: 6,
    category: 'social_media_automation',
    api_endpoint: 'https://api.missinglettr.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://missinglettr.com/developers',
  },

  // 7. CHAT + SUPPORT AI
  {
    id: 'chatbase',
    provider: 'chatbase',
    name: 'Chatbase',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.chatbase.co',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.chatbase.co',
  },
  {
    id: 'botpress',
    provider: 'botpress',
    name: 'Botpress',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.botpress.cloud',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://botpress.com/docs',
  },
  {
    id: 'rasa',
    provider: 'rasa',
    name: 'Rasa',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.rasa.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://rasa.com/docs',
  },
  {
    id: 'tidio',
    provider: 'tidio',
    name: 'Tidio API',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.tidio.co',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://developers.tidio.com',
  },
  {
    id: 'crisp',
    provider: 'crisp',
    name: 'Crisp Chat API',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.crisp.chat',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.crisp.chat',
  },
  {
    id: 'intercom',
    provider: 'intercom',
    name: 'Intercom API',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.intercom.io',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://developers.intercom.com',
  },
  {
    id: 'drift',
    provider: 'drift',
    name: 'Drift API',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.drift.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://developers.drift.com',
  },
  {
    id: 'kommunicate',
    provider: 'kommunicate',
    name: 'Kommunicate',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.kommunicate.io',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.kommunicate.io',
  },
  {
    id: 'manychat',
    provider: 'manychat',
    name: 'ManyChat',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.manychat.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://manychat.com/docs',
  },
  {
    id: 'landbot',
    provider: 'landbot',
    name: 'Landbot',
    category_id: 7,
    category: 'chat_support_ai',
    api_endpoint: 'https://api.landbot.io',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 2000,
    supported_request_types: ['chat'],
    requires_api_key: true,
    documentation_url: 'https://docs.landbot.io',
  },

  // 8. VOICE + TRANSLATION
  {
    id: 'google-speech',
    provider: 'google-speech',
    name: 'Google Speech-to-Text',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://speech.googleapis.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['voice', 'translation'],
    requires_api_key: true,
    documentation_url: 'https://cloud.google.com/speech-to-text/docs',
  },
  {
    id: 'whisper',
    provider: 'whisper',
    name: 'Whisper (OpenAI)',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api.openai.com/v1/audio',
    default_cost_per_1k_tokens: 0.006,
    default_max_tokens: 1000,
    supported_request_types: ['voice', 'translation'],
    requires_api_key: true,
    documentation_url: 'https://platform.openai.com/docs/guides/speech-to-text',
  },
  {
    id: 'assemblyai',
    provider: 'assemblyai',
    name: 'AssemblyAI',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api.assemblyai.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['voice', 'translation'],
    requires_api_key: true,
    documentation_url: 'https://docs.assemblyai.com',
  },
  {
    id: 'deepgram',
    provider: 'deepgram',
    name: 'Deepgram',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api.deepgram.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['voice', 'translation'],
    requires_api_key: true,
    documentation_url: 'https://developers.deepgram.com',
  },
  {
    id: 'elevenlabs',
    provider: 'elevenlabs',
    name: 'ElevenLabs (voice)',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api.elevenlabs.io',
    default_cost_per_1k_tokens: 0.015,
    default_max_tokens: 1000,
    supported_request_types: ['voice'],
    requires_api_key: true,
    documentation_url: 'https://docs.elevenlabs.io',
  },
  {
    id: 'azure-speech',
    provider: 'azure-speech',
    name: 'Azure Speech',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://eastus.api.cognitive.microsoft.com/sts/v1.0',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['voice', 'translation'],
    requires_api_key: true,
    documentation_url: 'https://docs.microsoft.com/azure/cognitive-services/speech-service',
  },
  {
    id: 'amazon-polly',
    provider: 'amazon-polly',
    name: 'Amazon Polly',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://polly.amazonaws.com',
    default_cost_per_1k_tokens: 0.004,
    default_max_tokens: 1000,
    supported_request_types: ['voice'],
    requires_api_key: true,
    documentation_url: 'https://docs.aws.amazon.com/polly',
  },
  {
    id: 'google-translate',
    provider: 'google-translate',
    name: 'Google Translate API',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://translation.googleapis.com',
    default_cost_per_1k_tokens: 0.002,
    default_max_tokens: 1000,
    supported_request_types: ['translation'],
    requires_api_key: true,
    documentation_url: 'https://cloud.google.com/translate/docs',
  },
  {
    id: 'deepl',
    provider: 'deepl',
    name: 'DeepL API',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api-free.deepl.com',
    default_cost_per_1k_tokens: 0.003,
    default_max_tokens: 1000,
    supported_request_types: ['translation'],
    requires_api_key: true,
    documentation_url: 'https://developers.deepl.com',
  },
  {
    id: 'rev-ai',
    provider: 'rev-ai',
    name: 'Rev.ai',
    category_id: 8,
    category: 'voice_translation',
    api_endpoint: 'https://api.rev.ai',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['voice'],
    requires_api_key: true,
    documentation_url: 'https://docs.rev.ai',
  },

  // 9. IMAGE / DESIGN AI (FOR MARKETING)
  {
    id: 'stability-ai',
    provider: 'stability-ai',
    name: 'Stability AI',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.stability.ai',
    default_cost_per_1k_tokens: 0.02,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://platform.stability.ai/docs',
  },
  {
    id: 'midjourney',
    provider: 'midjourney',
    name: 'Midjourney (via bridge)',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.midjourney.com',
    default_cost_per_1k_tokens: 0.03,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://docs.midjourney.com',
  },
  {
    id: 'dalle',
    provider: 'dalle',
    name: 'DALL·E',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.openai.com/v1/images',
    default_cost_per_1k_tokens: 0.04,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://platform.openai.com/docs/guides/images',
  },
  {
    id: 'leonardo-ai',
    provider: 'leonardo-ai',
    name: 'Leonardo AI',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.leonardo.ai',
    default_cost_per_1k_tokens: 0.015,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://docs.leonardo.ai',
  },
  {
    id: 'runway-ml',
    provider: 'runway-ml',
    name: 'Runway ML',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.runwayml.com',
    default_cost_per_1k_tokens: 0.025,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://docs.runwayml.com',
  },
  {
    id: 'canva',
    provider: 'canva',
    name: 'Canva API',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.canva.com',
    default_cost_per_1k_tokens: 0.01,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://developers.canva.com',
  },
  {
    id: 'remove-bg',
    provider: 'remove-bg',
    name: 'Remove.bg',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.remove.bg',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://www.remove.bg/api',
  },
  {
    id: 'clipdrop',
    provider: 'clipdrop',
    name: 'Clipdrop',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://clipdrop-api.co',
    default_cost_per_1k_tokens: 0.01,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://clipdrop.com/apis',
  },
  {
    id: 'bannerbear',
    provider: 'bannerbear',
    name: 'Bannerbear',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.bannerbear.com',
    default_cost_per_1k_tokens: 0.008,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://bannerbear.com/docs',
  },
  {
    id: 'pixelcut',
    provider: 'pixelcut',
    name: 'Pixelcut',
    category_id: 9,
    category: 'image_design_ai',
    api_endpoint: 'https://api.pixelcut.com',
    default_cost_per_1k_tokens: 0.005,
    default_max_tokens: 1000,
    supported_request_types: ['image'],
    requires_api_key: true,
    documentation_url: 'https://pixelcut.com/docs',
  },

  // 10. AUTOMATION + WORKFLOW
  {
    id: 'zapier',
    provider: 'zapier',
    name: 'Zapier API',
    category_id: 10,
    category: 'automation_workflow',
    api_endpoint: 'https://api.zapier.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developer.zapier.com',
  },
  {
    id: 'make',
    provider: 'make',
    name: 'Make (Integromat)',
    category_id: 10,
    category: 'automation_workflow',
    api_endpoint: 'https://api.make.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://developers.make.com',
  },
  {
    id: 'n8n',
    provider: 'n8n',
    name: 'n8n',
    category_id: 10,
    category: 'automation_workflow',
    api_endpoint: 'https://api.n8n.io',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.n8n.io',
  },
  {
    id: 'pipedream',
    provider: 'pipedream',
    name: 'Pipedream',
    category_id: 10,
    category: 'automation_workflow',
    api_endpoint: 'https://api.pipedream.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://docs.pipedream.com',
  },
  {
    id: 'ifttt',
    provider: 'ifttt',
    name: 'IFTTT API',
    category_id: 10,
    category: 'automation_workflow',
    api_endpoint: 'https://api.ifttt.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://platform.ifttt.com/developer',
  },

  // 11. ANALYTICS + TRACKING
  {
    id: 'google-analytics',
    provider: 'google-analytics',
    name: 'Google Analytics API',
    category_id: 11,
    category: 'analytics_tracking',
    api_endpoint: 'https://analyticsreporting.googleapis.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://developers.google.com/analytics',
  },
  {
    id: 'mixpanel',
    provider: 'mixpanel',
    name: 'Mixpanel',
    category_id: 11,
    category: 'analytics_tracking',
    api_endpoint: 'https://api.mixpanel.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://developer.mixpanel.com',
  },
  {
    id: 'amplitude',
    provider: 'amplitude',
    name: 'Amplitude',
    category_id: 11,
    category: 'analytics_tracking',
    api_endpoint: 'https://api.amplitude.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://developers.amplitude.com',
  },
  {
    id: 'posthog',
    provider: 'posthog',
    name: 'PostHog',
    category_id: 11,
    category: 'analytics_tracking',
    api_endpoint: 'https://api.posthog.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://posthog.com/docs/api',
  },
  {
    id: 'plausible',
    provider: 'plausible',
    name: 'Plausible',
    category_id: 11,
    category: 'analytics_tracking',
    api_endpoint: 'https://plausible.io/api',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://plausible.io/docs/api',
  },

  // 12. BONUS (HIGH IMPACT)
  {
    id: 'stripe',
    provider: 'stripe',
    name: 'Stripe (billing AI triggers)',
    category_id: 12,
    category: 'bonus_high_impact',
    api_endpoint: 'https://api.stripe.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://stripe.com/docs/api',
  },
  {
    id: 'razorpay',
    provider: 'razorpay',
    name: 'Razorpay API',
    category_id: 12,
    category: 'bonus_high_impact',
    api_endpoint: 'https://api.razorpay.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://razorpay.com/docs/api',
  },
  {
    id: 'firebase',
    provider: 'firebase',
    name: 'Firebase (realtime)',
    category_id: 12,
    category: 'bonus_high_impact',
    api_endpoint: 'https://firebase.google.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://firebase.google.com/docs',
  },
  {
    id: 'supabase',
    provider: 'supabase',
    name: 'Supabase (DB + auth)',
    category_id: 12,
    category: 'bonus_high_impact',
    api_endpoint: 'https://api.supabase.com',
    default_cost_per_1k_tokens: 0,
    default_max_tokens: 1000,
    supported_request_types: ['automation'],
    requires_api_key: true,
    documentation_url: 'https://supabase.com/docs',
  },
  {
    id: 'algolia',
    provider: 'algolia',
    name: 'Algolia (search AI)',
    category_id: 12,
    category: 'bonus_high_impact',
    api_endpoint: 'https://api.algolia.com',
    default_cost_per_1k_tokens: 0.001,
    default_max_tokens: 1000,
    supported_request_types: ['analytics'],
    requires_api_key: true,
    documentation_url: 'https://algolia.com/doc',
  },
];

// Default usage mapping
export const DEFAULT_USAGE_MAPPING: {
  [key in RequestType]: {
    preferred_provider: string;
    fallback_providers: string[];
  };
} = {
  seo: {
    preferred_provider: 'deepseek', // Cheapest
    fallback_providers: ['groq', 'mistral', 'together-ai'],
  },
  chat: {
    preferred_provider: 'groq', // Fast
    fallback_providers: ['deepseek', 'together-ai', 'openai'],
  },
  critical: {
    preferred_provider: 'openai', // Best quality
    fallback_providers: ['anthropic-claude', 'google-gemini', 'openrouter'],
  },
  image: {
    preferred_provider: 'stability-ai',
    fallback_providers: ['leonardo-ai', 'dalle', 'runway-ml'],
  },
  voice: {
    preferred_provider: 'whisper',
    fallback_providers: ['google-speech', 'deepgram', 'assemblyai'],
  },
  translation: {
    preferred_provider: 'google-translate',
    fallback_providers: ['deepl', 'google-gemini'],
  },
  automation: {
    preferred_provider: 'zapier',
    fallback_providers: ['make', 'n8n', 'pipedream'],
  },
  analytics: {
    preferred_provider: 'google-analytics',
    fallback_providers: ['mixpanel', 'amplitude', 'posthog'],
  },
};
