-- Programmable Pages Table for Module 101: Global Programmable Page Factory
-- This table stores auto-generated pages for SEO scaling

CREATE TABLE IF NOT EXISTS programmable_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Page Identification
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  page_type TEXT NOT NULL, -- 'service', 'location', 'service-location', 'niche'
  
  -- Targeting
  base_keyword TEXT NOT NULL, -- e.g., 'crm-software'
  country_code TEXT, -- e.g., 'IN', 'US', 'AE'
  city TEXT, -- e.g., 'mumbai', 'delhi'
  language_code TEXT DEFAULT 'en', -- e.g., 'en', 'hi', 'ar'
  
  -- SEO Data
  meta_title TEXT,
  meta_description TEXT,
  meta_keywords TEXT[], -- Array of keywords
  hashtags TEXT[], -- Array of hashtags
  schema_markup JSONB, -- JSON-LD schema
  
  -- Content
  content TEXT, -- Generated content
  content_template TEXT, -- Template used for generation
  
  -- Status
  status TEXT DEFAULT 'draft', -- 'draft', 'published', 'indexed', 'archived'
  is_active BOOLEAN DEFAULT true,
  
  -- Indexing
  indexed_at TIMESTAMP WITH TIME ZONE,
  index_status TEXT DEFAULT 'pending', -- 'pending', 'indexed', 'failed'
  
  -- Performance
  seo_score INTEGER DEFAULT 0, -- 0-100
  traffic_estimate INTEGER DEFAULT 0,
  backlinks_count INTEGER DEFAULT 0,
  
  -- Relationships
  product_id UUID REFERENCES marketplace_products(id) ON DELETE CASCADE,
  parent_page_id UUID REFERENCES programmable_pages(id) ON DELETE CASCADE,
  
  -- Automation
  auto_generated BOOLEAN DEFAULT false,
  auto_index_enabled BOOLEAN DEFAULT false,
  auto_update_enabled BOOLEAN DEFAULT false,
  last_auto_update TIMESTAMP WITH TIME ZONE,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  published_at TIMESTAMP WITH TIME ZONE,
  
  -- Metadata
  generation_source TEXT, -- 'manual', 'ai', 'template'
  generation_metadata JSONB,
  
  -- Constraints
  CONSTRAINT valid_status CHECK (status IN ('draft', 'published', 'indexed', 'archived')),
  CONSTRAINT valid_index_status CHECK (index_status IN ('pending', 'indexed', 'failed')),
  CONSTRAINT valid_seo_score CHECK (seo_score >= 0 AND seo_score <= 100)
);

-- Indexes for performance
CREATE INDEX idx_programmable_pages_slug ON programmable_pages(slug);
CREATE INDEX idx_programmable_pages_status ON programmable_pages(status);
CREATE INDEX idx_programmable_pages_country ON programmable_pages(country_code);
CREATE INDEX idx_programmable_pages_keyword ON programmable_pages(base_keyword);
CREATE INDEX idx_programmable_pages_product_id ON programmable_pages(product_id);
CREATE INDEX idx_programmable_pages_page_type ON programmable_pages(page_type);
CREATE INDEX idx_programmable_pages_seo_score ON programmable_pages(seo_score);
CREATE INDEX idx_programmable_pages_created_at ON programmable_pages(created_at DESC);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_programmable_pages_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at
CREATE TRIGGER programmable_pages_updated_at_trigger
  BEFORE UPDATE ON programmable_pages
  FOR EACH ROW
  EXECUTE FUNCTION update_programmable_pages_updated_at();

-- Comments
COMMENT ON TABLE programmable_pages IS 'Stores auto-generated SEO pages for global scaling';
COMMENT ON COLUMN programmable_pages.slug IS 'URL slug for the page';
COMMENT ON COLUMN programmable_pages.page_type IS 'Type of programmable page (service, location, service-location, niche)';
COMMENT ON COLUMN programmable_pages.base_keyword IS 'Base keyword used for page generation';
COMMENT ON COLUMN programmable_pages.country_code IS 'Target country code (ISO 2-letter)';
COMMENT ON COLUMN programmable_pages.city IS 'Target city name';
COMMENT ON COLUMN programmable_pages.language_code IS 'Target language code (ISO 2-letter)';
COMMENT ON COLUMN programmable_pages.seo_score IS 'SEO score from 0-100';
COMMENT ON COLUMN programmable_pages.auto_generated IS 'Whether page was auto-generated by AI';
COMMENT ON COLUMN programmable_pages.auto_index_enabled IS 'Whether auto-indexing is enabled for this page';
