/**
 * atomic-payment edge function
 *
 * Delegates the entire payment → order → license → wallet flow
 * to the PostgreSQL function `process_wallet_payment`, which runs inside
 * a single database transaction with row-level locking.
 *
 * Route: POST /functions/v1/atomic-payment
 *
 * Body:
 *   product_id       string (UUID)
 *   duration_days    number  (30 | 90 | 180 | 365)
 *   amount           number
 *   idempotency_key  string  (UUID generated by the client)
 *
 * Enforces:
 *  - JWT authentication (no guest purchases)
 *  - Server-side rate limiting (5 attempts / 60 s per user)
 *  - Input validation (UUIDs, positive amount, valid duration)
 *  - Idempotency (same key → same result, no duplicate order)
 *  - Feature-flag check ('payment_wallet' must be enabled)
 *  - IP logging + audit
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type, x-idempotency-key',
  'Content-Type': 'application/json',
};

/** In-memory rate-limit store (per isolate; resets on cold start). */
const rateLimitStore = new Map<string, { count: number; resetAt: number }>();
const RATE_LIMIT    = 5;
const WINDOW_MS     = 60_000;

function trimStore(now: number) {
  for (const [k, v] of rateLimitStore) {
    if (v.resetAt <= now) rateLimitStore.delete(k);
  }
}

function isRateLimited(key: string): boolean {
  const now = Date.now();
  trimStore(now);

  const entry = rateLimitStore.get(key);
  if (!entry || entry.resetAt <= now) {
    rateLimitStore.set(key, { count: 1, resetAt: now + WINDOW_MS });
    return false;
  }
  if (entry.count >= RATE_LIMIT) return true;
  entry.count++;
  return false;
}

function ok(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), { status, headers: corsHeaders });
}

function fail(message: string, status = 400) {
  return new Response(JSON.stringify({ success: false, error: message }), {
    status,
    headers: corsHeaders,
  });
}

function isUuid(v: unknown): v is string {
  return (
    typeof v === 'string' &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)
  );
}

const VALID_DURATIONS = new Set([30, 60, 90, 180, 365]);

Deno.serve(async (req) => {
  // ── CORS preflight ──
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return fail('Method not allowed', 405);
  }

  // ── Authenticate ──
  const authHeader = req.headers.get('Authorization') ?? '';
  if (!authHeader.startsWith('Bearer ')) return fail('Unauthorized', 401);

  const adminSb = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  const token = authHeader.replace('Bearer ', '').trim();
  const { data: authData, error: authError } = await adminSb.auth.getUser(token);
  if (authError || !authData?.user) return fail('Unauthorized', 401);

  const userId = authData.user.id;

  // ── Check session revocation ──
  const { data: revoked } = await adminSb
    .from('revoked_sessions')
    .select('id')
    .eq('user_id', userId)
    .gt('revoked_before', new Date(authData.user.created_at).toISOString())
    .limit(1)
    .maybeSingle();

  if (revoked) return fail('Session has been revoked. Please log in again.', 401);

  // ── Rate limit ──
  if (isRateLimited(`payment:${userId}`)) {
    return fail('Too many payment attempts. Please wait before trying again.', 429);
  }

  // ── Parse + validate body ──
  let body: any;
  try {
    body = await req.json();
  } catch {
    return fail('Invalid JSON body');
  }

  const { product_id, duration_days, amount, idempotency_key } = body ?? {};

  if (!isUuid(product_id))         return fail('product_id must be a valid UUID');
  if (!isUuid(idempotency_key))    return fail('idempotency_key must be a valid UUID');
  if (!VALID_DURATIONS.has(Number(duration_days)))
    return fail(`duration_days must be one of: ${[...VALID_DURATIONS].join(', ')}`);
  const numAmount = Number(amount);
  if (!Number.isFinite(numAmount) || numAmount <= 0)
    return fail('amount must be a positive number');

  // ── Feature flag: wallet payments must be enabled ──
  const { data: flag } = await adminSb
    .from('feature_flags')
    .select('is_enabled')
    .eq('flag_key', 'payment_wallet')
    .maybeSingle();

  if (!flag?.is_enabled) {
    return fail('Wallet payments are currently disabled. Please try another payment method.', 503);
  }

  // ── Check geo block (IP-based, best-effort) ──
  const clientIp = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? null;

  // ── Abuse check: is user currently blocked? ──
  const { data: abuseBlock } = await adminSb
    .from('abuse_rate_limits')
    .select('blocked_until')
    .eq('user_id', userId)
    .eq('action_type', 'payment_attempt')
    .gt('blocked_until', new Date().toISOString())
    .limit(1)
    .maybeSingle();

  if (abuseBlock) {
    return fail('Account temporarily blocked due to suspicious activity. Contact support.', 403);
  }

  // ── Verify product exists and is not deleted/inactive ──
  const { data: product, error: prodError } = await adminSb
    .from('products')
    .select('id, name, is_active, deleted_at')
    .eq('id', product_id)
    .maybeSingle();

  if (prodError || !product) return fail('Product not found', 404);
  if (!product.is_active || product.deleted_at) return fail('Product is no longer available', 410);

  // ── Verify pricing matches what the client submitted ──
  const { data: pricing } = await adminSb
    .from('product_pricing')
    .select('base_price')
    .eq('product_id', product_id)
    .eq('duration_days', Number(duration_days))
    .maybeSingle();

  if (pricing && Math.abs(pricing.base_price - numAmount) > 0.01) {
    return fail(
      `Amount mismatch. Expected ${pricing.base_price}, received ${numAmount}`,
    );
  }

  // ── Call atomic payment PL/pgSQL function ──
  const { data: result, error: fnError } = await adminSb.rpc('process_wallet_payment', {
    p_user_id:         userId,
    p_product_id:      product_id,
    p_duration_days:   Number(duration_days),
    p_amount:          numAmount,
    p_idempotency_key: idempotency_key,
  });

  if (fnError) {
    // Log failure in admin alerts (best-effort)
    await adminSb.from('audit_logs').insert({
      user_id:     userId,
      action:      'PAYMENT_FAILED',
      entity_type: 'order',
      entity_id:   null,
      new_data: {
        product_id,
        amount:          numAmount,
        duration_days:   Number(duration_days),
        idempotency_key,
        error:           fnError.message,
        ip:              clientIp,
      },
    }).then(() => null);

    return fail(fnError.message || 'Payment processing failed', 500);
  }

  if (!result?.success) {
    return fail(result?.error ?? 'Payment processing failed', 402);
  }

  // ── Record IP for audit (non-blocking) ──
  adminSb.from('audit_logs').insert({
    user_id:     userId,
    action:      'PURCHASE',
    entity_type: 'order',
    entity_id:   result.order_id,
    ip_address:  clientIp,
    new_data: {
      product_id,
      amount:        numAmount,
      duration_days: Number(duration_days),
      idempotent:    result.idempotent ?? false,
    },
  }).then(() => null);

  return ok({
    success:     true,
    order_id:    result.order_id,
    license_key: result.license_key,
    expires_at:  result.expires_at,
    idempotent:  result.idempotent ?? false,
  });
});
